name: my-workflow-name

on:
  push:
    branches:
      - all
      - '*'
  pull_request:
    branches: [ all ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install llvm-dev
      run: sudo apt-get install llvm-dev
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: mkdir build
      run: mkdir build && mkdir build/test
    - name: test
      run: ls -l; ls -l build; llvm-config --cxxflags --ldflags --system-libs --libs core
    - uses: actions/checkout@v1
    - name: make test
      run: make CI
    - name: Run Test
      run: /home/runner/work/github_actions_gtest_example/github_actions_gtest_example/build/test/github_actions_gtest_example.test
